use CartoonsDatabase

SET TRANSACTION ISOLATION LEVEL SNAPSHOT
BEGIN TRAN
SELECT * FROM CREATORS WHERE CreatorId=1

--- DO SOME WORK

SELECT * FROM CREATORS
WHERE CreatorId=1

UPDATE CREATORS SET Name='Mariaaa' 
WHERE CreatorId=1

COMMIT TRAN
